export const PIZZAS = {
  TOPPINGS: [
    'Bacon',
    'Black Forest Ham',
    'Grilled Rosemary Chicken Breast',
    'Italian Sausage',
    'Pepperoni',
    'Smoked Salmon',
    'Vegan Sausage',
    'None',
  ],
  CHEESES: [
    'Mozzarella Cheese',
    'Mozzarella Cheese, Fontina Cheese, Parmesan, Gruyere Cheese',
    'Vegan Mozzarella Cheese',
    'No Cheese',
  ],
  SAUCES: [
    'BBQ Sauce',
    'Bechamel Sauce',
    'Buffalo Sauce',
    'Dill & Shallot Cream Cheese',
    'Pesto Sauce',
    'Smoked Tomato Sauce',
    'Spicy Marinara Sauce',
    'No Sauce',
  ],
  ADD_ONS: [
    'Basil',
    'Mixed Peppers',
    'Mushroom',
    'Pineapple',
    'Ranch Dressing',
    'Red Onion',
    'Sliced Black Olives',
    'Sliced Jalapeño',
    'Tomato',
  ],
}
