export const SALADS = {
  GREENS: [
    'Baby Spinach',
    'Mesclun Mix Lettuce',
    'Power Greens Blend',
    'Romaine Lettuce',
  ],
  PROTEINS: [
    'Avocado',
    'Dijon Tempeh',
    'Dill Salmon',
    'Grilled Rosemary Chicken Breast',
    'Peppered Steak',
    'Vegan Sausage',
    'None',
  ],
  TOPPINGS: [
    'Black Lentils',
    'Bleu Cheese',
    'Candied Walnuts',
    'Cucumber',
    'Dried Cranberries',
    'Farro',
    'Garbanzo Beans',
    'Goat Cheese',
    'Grape Tomato',
    'Hard Boiled Egg',
    'Red Cabbage',
    'Red Onion',
    'Roasted Golden Beets',
    'Sliced Black Olives',
  ],
  DRESSINGS: [
    'Balsamic Vinaigrette',
    'Caesar Dressing',
    'Lemon Oregano Vinaigrette',
    'Ranch Dressing',
    'Roasted Red Pepper Dressing',
    'None',
  ],
}
