export const SANDWICHES = {
  BREADS: ['Country Loaf', 'Wheat Torpedo Hoagie Roll', 'Whole Wheat Bread'],
  CHEESES: [
    'Cheddar Cheese',
    'Mozzarella Cheese',
    'Provolone Cheese',
    'Vegan Cheddar Cheese',
    'None',
  ],
  TOPPINGS: [
    'Avocado Pulp',
    'Bacon',
    'Black Forest Ham',
    'Egg Salad',
    'Grilled Rosemary Chicken Breast',
    'Pepperoni',
    'Prosciutto',
    'Roast Beef',
    'Turkey',
  ],
  ADD_ONS: [
    'Baby Spinach',
    'Cucumber',
    'Mixed Peppers',
    'Pepperoncini',
    'Pickles',
    'Red Onion',
    'Romaine Lettuce',
    'Sliced Black Olives',
    'Sliced Jalepeno',
    'Tomatoes',
  ],
  SPREADS: [
    'Balsamic Vinegar',
    'Mayonnaise',
    'Mustard',
    'Olive Oil',
    'Olive Salad',
    'Pesto Sauce',
    'Red Wine Vinegar',
    'Sun Dried Tomato Pesto',
  ],
}
